// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempusDemoArchive.Persistence;

#nullable disable

namespace TempusDemoArchive.Persistence.Migrations
{
    [DbContext(typeof(ArchiveDbContext))]
    [Migration("20260125094116_AddWrHistoryIndexes")]
    partial class AddWrHistoryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.Demo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Date")
                        .HasColumnType("REAL");

                    b.Property<bool>("StvFailed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StvFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StvProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Demos");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.Stv", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExtractedFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IntervalPerTick")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ParsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartTick")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemoId");

                    b.ToTable("Stvs");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvChat", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tick")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemoId", "Index");

                    b.HasIndex("FromUserId");

                    b.HasIndex("Text")
                        .HasDatabaseName("IX_StvChats_Text_TempusWr")
                        .HasFilter("Text LIKE 'Tempus | (%'");

                    b.HasIndex("Tick");

                    b.ToTable("StvChats");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvChatResolution", b =>
                {
                    b.Property<int?>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateUserIdsCsv")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolvedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tick")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("StvChatResolution", (string)null);
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvDeath", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssisterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KillerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VictimUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemoId", "Index");

                    b.ToTable("StvDeaths");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvPause", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToTick")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemoId", "Index");

                    b.ToTable("StvPauses");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvSpawn", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemoId", "Index");

                    b.ToTable("StvSpawns");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvTeamChange", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTeam")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disconnect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Silent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemoId", "Index");

                    b.ToTable("StvTeamChanges");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvUser", b =>
                {
                    b.Property<long>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SteamId64")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamIdClean")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamIdKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemoId", "UserId");

                    b.HasIndex("SteamId64");

                    b.ToTable("StvUsers");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.Stv", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.Demo", "Demo")
                        .WithOne("Stv")
                        .HasForeignKey("TempusDemoArchive.Persistence.Models.STVs.Stv", "DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TempusDemoArchive.Persistence.Models.STVs.StvHeader", "Header", b1 =>
                        {
                            b1.Property<long>("StvDemoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DemoType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double?>("Duration")
                                .HasColumnType("REAL");

                            b1.Property<int?>("Frames")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Game")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Map")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nick")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Protocol")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Server")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Signon")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Ticks")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Version")
                                .HasColumnType("INTEGER");

                            b1.HasKey("StvDemoId");

                            b1.HasIndex("Map")
                                .HasDatabaseName("IX_Stvs_Header_Map");

                            b1.HasIndex("Server")
                                .HasDatabaseName("IX_Stvs_Header_Server");

                            b1.ToTable("Stvs");

                            b1.WithOwner()
                                .HasForeignKey("StvDemoId");
                        });

                    b.Navigation("Demo");

                    b.Navigation("Header")
                        .IsRequired();
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvChat", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", "Stv")
                        .WithMany("Chats")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvDeath", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", "Stv")
                        .WithMany("Deaths")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvPause", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", "Stv")
                        .WithMany("Pauses")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvSpawn", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", "Stv")
                        .WithMany("Spawns")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvTeamChange", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", "Stv")
                        .WithMany("TeamChanges")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.StvUser", b =>
                {
                    b.HasOne("TempusDemoArchive.Persistence.Models.STVs.Stv", null)
                        .WithMany("Users")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.Demo", b =>
                {
                    b.Navigation("Stv");
                });

            modelBuilder.Entity("TempusDemoArchive.Persistence.Models.STVs.Stv", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Deaths");

                    b.Navigation("Pauses");

                    b.Navigation("Spawns");

                    b.Navigation("TeamChanges");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
